### ISSUE TITLE
Can't export

### ISSUE THREAD

**Issue by CreeperArcade** [nesrak1/UABEA#203]

**Comment by nesrak1** [comment]
Was the problem actually fixed?

**Comment by CreeperArcade** [comment]
> Was the problem actually fixed?
Not really. I wanted to export just one file after decompiling a .unity3D file but after pressing the export button the app would just close. I worked around it by exporting all and only using the file I wanted. 
I've got an unrelated question if you don't mind answering. After decompiling the .unity3D file, exporting and editing the file I wanted to, to recompile the apk and make it work I think have to recompile the exported files back to .unity3D, no? How do I do this? Or is it something else that I'm meant to do?

**Comment by nesrak1** [comment]
You're right that export seems broken right now. I've pushed a fix just now and I'll reupload the release files in a second.

I also want to mention that if you want to edit the file in the bundle without exporting, you can do that by clicking the Info button. I almost never use the export button, so I guess I missed trying to use it during testing.

Also, please don't close an issue just because you found a workaround. If I don't fix the issue now, many other people are going to submit issues just like this one until they also find the workaround themselves which is not ideal.
