### ISSUE TITLE
New addressables uses hash in header

### ISSUE THREAD

**Issue by ppng222** [nesrak1/UABEA#204]
I was trying to extract files from the Switch version of Just Dance 2023 when I noticed the game uses addressables with a hash for the first 32 bytes. The program can't load these unless I replace the hash with a new header, maybe there is a way to bypass this header or reverse engineer it?

<img width="497" alt="image" src="https://user-images.githubusercontent.com/76928655/203635996-1152107b-768a-41d2-aa57-a7813a501347.png">
<img width="515" alt="image" src="https://user-images.githubusercontent.com/76928655/203636307-1c42d64e-7921-4ee1-8616-6fcae6eb6d94.png">

**Comment by nesrak1** [comment]
Most likely the game encrypted or randomized the first 32 bytes as a simple protection to prevent opening it with tools. The good news is that bundles should have the same first 32 bytes since it's mainly just the engine version the game uses. Even better, I happen to have a game using 2021.3.9f1 exactly like your screenshot shows and it should be just this:

![image](https://user-images.githubusercontent.com/12544505/203638364-1b06b0c0-36cd-44b3-8f79-36054f911e4e.png)

So you could just overwrite the first 32 bytes with that probably. Anything else that might not work because of a custom engine is not something I'll support.
