### ISSUE TITLE
Export Dump does not have a popover

### ISSUE THREAD

**Issue by lswd** [nesrak1/UABEA#211]
When exporting MonoBehaviour files using Export Dump, pop-ups are not performed
However, when I use UABE, the following popup will pop up. Does UABEA export MonoBehaviour files without popup? It is my computer's problem.

![1671850969512](https://user-images.githubusercontent.com/24218775/209419031-b02a3dee-2e32-4675-92dc-e209e4a2c849.png)

**Comment by nesrak1** [comment]
UABEA and UABE do not use the same code at all. Because UABE is C++, it needs to call a C# tool which uses Mono.Cecil. Since UABEA is fully C# (as the name implies), all of this is pretty much automatic and in the background when needed. The only difference is I don't ask _where_ to load assemblies since it's almost always the same location and most people I talked to would rather have it automatic and move the files when needed.

All this to say this isn't an actual issue. The question `Does UABEA export MonoBehaviour files without popup?` could have been easily determined without making an issue on here by just... trying to export and seeing if it comes out the way you expect (i.e. the same as UABE's output).

If it doesn't come out as you expect, that's a totally different issue. But the way you worded the issue, it seems you don't even know.
