### ISSUE TITLE
LZ4 compression error

### ISSUE THREAD

**Issue by c0nd3v** [nesrak1/UABEA#214]
Hello, I tried using Asset Studio to unpack a bundle that I edited with UABEA. I get the following error:

![image](https://user-images.githubusercontent.com/32241825/211179500-bae16a42-2cc6-4b4a-9d59-b7b103a7f21b.png)

Is this a problem with UABEA or Asset Studio?

(Unity game has no problem loading this bundle, only Asset Studio)

**Comment by nesrak1** [comment]
If you have the latest asset studio and latest uabea and it's still doing this, it might be a problem with uabea (or at least the lz4 compression library I use.) It's hard to debug these kinds of things because the issue could be anywhere.

**Comment by nesrak1** [comment]
Someone else brought this up to me and it seems like this happens the compress function overwrites the original file but does not trim it. It turns out someone else reported this fix to me, so it was fixed way back in April before release 6. So I'm going to close this issue now. If someone else sees this in the future, I think just decompressing and recompressing the bundle will fix it.
