### ISSUE TITLE
Container field blank when viewing decompressed asset bundles from Enter the Gungeon.

### ISSUE THREAD

**Issue by ApacheThunder** [nesrak1/UABEA#216]
I've had v2.2 of the original UABE and the container section of the dialog I've used to sort things based on asset path. This has made finding things easier.

It appears this is not working correctly on Enter the Gungeon's assetbundles though with UABEA. Gungeon uses a 2017 build of Unity Engine by the way.

This is really the only thing turning me off from using this. That and lack of abiliy to sort alphabetically the assets viewed in the Scene Hierarchy dialog.

**Comment by nesrak1** [comment]
> It appears this is not working correctly on Enter the Gungeon's assetbundles though with UABEA. Gungeon uses a 2017 build of Unity Engine by the way.

It's working for me in enter the gungeon, although if you sort by container, you'll have to scroll to the bottom of the list because the data grid puts empty string above all other strings for some reason. If you're confused as to why there aren't as many container entries, that's because I'm only handling the main container object and not any dependencies. So for example, if you had a material that used a texture and only the material had a path, UABE would show the texture as a dependency to the material, but UABEA will only show the material's container path. I'll probably make this a toggle in the future.

> That and lack of abiliy to sort alphabetically the assets viewed in the Scene Hierarchy dialog.

I never really thought about this since most of the time I'm using that dialog in level files where the ordering is the same as original. If you're in bundles, you're right that it would make more sense to have some kind of sort option. I also plan on having a button in the list view that selects the correct gameobject in the hierarchy window.

**Comment by nesrak1** [comment]
I forgot to add that exporting files and opening them outside of the bundle will make the container paths not show up. This is something that will be fixed soon.

(This is because the code checks whether to look for an AssetBundle asset or the globalgamemanagers file for container strings by checking if the file is in a bundle or not, rather than if the AssetBundle asset exists. In the real world, there would never be a file outside of a bundle like this, but when exporting it for editing purposes, it can be annoying.)

**Comment by nesrak1** [comment]
This should be fixed. Scene Hierarchy doesn't support sorting still but that may be a little hard to implement (especially to be able to unsort it back to original order).

That should probably have its own issue.
