### ISSUE TITLE
Failed to encode texture format BC6H

### ISSUE THREAD

**Issue by repinek** [nesrak1/UABEA#254]
i tried change texture2D and this happened, i use texture format bc6h

**Comment by nesrak1** [comment]
I don't think BC6H is a supported encoding format for UABEA (none of the libraries handle it right now)

**Comment by nesrak1** [comment]
These are all unsupported: https://github.com/nesrak1/UABEA/blob/master/TexturePlugin/TextureEncoderDecoder.cs#L513-L518

**Comment by repinek** [comment]
//pls don't use what this mean xd

**Comment by nesrak1** [comment]
This means don't use it because it's unsupported

**Comment by nesrak1** [comment]
Since this has popped back up in my notifications, I wanted to add that AssetsTools.NET now supports BC6H. As of last check, BC6H passed the tests: https://github.com/nesrak1/AssetsTools.NET/blob/669349bc99e32ada8d2f443c98c4dfeddb02baee/AssetsTools.NET.Tests/Texture.cs#L34 . That means it should be working in UABEANext as of right now.

**Comment by repinek** [comment]
haha, anyway BC7 works perfectly in my case
Thanks for this great program!
