### ISSUE TITLE
StandaloneWindows64 file increase and game problem

### ISSUE THREAD

**Issue by LauraZaguini** [nesrak1/UABEA#300]
Firstly, I want to start by saying that perhaps this is not the appropriate place to make this type of announcement.

But I'm wanting to translate an indie game using UEBEA, but when I open the .bundle with all the necessary files I need to do the translation. When I open the correct file, export what I need, change the file I want and then import and save the .bundle, the file ends up increasing from 32kb to 70kb, when I start the game, it ends up freezing the game and making it impossible to do anything, having to close the game again and open it to give the same problem.

By the way, I read about addressables but I didn't understand how it works, I ended up downloading the CRC tool and I didn't understand how it works, a better guide in the future, maybe?

**Comment by nesrak1** [comment]
The size increase is normal because while editing, the bundle is decomposed until you use the compress option in the main window. As for addressables tools, if you look at the first issue in that repo, there is a video someone made of you need help with the command line tool. In the future, this will be automatic.
