### ISSUE TITLE
can not be opened

### ISSUE THREAD

**Issue by paxlleyy** [nesrak1/UABEA#378]
how to run uabea on emulator, like winlator or mobox?
I have tried various ways but the results are still zero, please help me, i really need a compression mode here

**Comment by nesrak1** [comment]
If you're asking how to run this on android, why not use the Linux version instead of trying to emulate both windows _and_ x86 🤨🤨🤨.

Either [andronix with termux](https://play.google.com/store/apps/details?id=studio.com.techriz.andronix) or [userland](https://play.google.com/store/apps/details?id=tech.ula) are enough to get at least a desktop environment with dotnet installed. Then, use the ubuntu release build of uabea (you don't have to use ubuntu but it's recommended.)

Note that texture plugins won't work, but compression is fine.

**Comment by paxlleyy** [comment]
I have installed ubuntu but how to build uabea?,or how to run uabea?
sorry if this is a stupid question, because i have never used ubuntu before😓
