### ISSUE TITLE
2021.1.f1 rename texture fail

### ISSUE THREAD

**Issue by GOALARG** [nesrak1/UABEA#58]
[check.zip](https://github.com/nesrak1/UABEA/files/6633668/check.zip)
can u try change texture name via plugin?

**Comment by nesrak1** [comment]
The edit texture plugin isn't fully complete, so most of the fields don't edit like the name. Not sure why you need to change the name, but I can add it when I get around to it.

**Comment by PipoCrazy** [comment]
You have probably saved me 10+ hours of work. I shouldn´t have modified the texture names in my files, but it will be easy to rename them to their original names rather than importing all of them one by one each time the game updates.

Thank you very much and I hope that this project keeps growing up. I have found a lot of joy in modding Unity games.

Cheers!

**Comment by nesrak1** [comment]
You can change name now, for whatever reasons...
