### ISSUE TITLE
audio bug

### ISSUE THREAD

**Issue by Make1860** [nesrak1/UABEA#75]
After audio replacement, GUI plays normally and the game always exits

**Comment by nesrak1** [comment]
Audio replacement? Did you dump from one game and import into another? You need to give me a bit more info on what you did if you want help.

**Comment by Make1860** [comment]
> 音频替换？您是否从一款游戏中转储并导入到另一款游戏中？如果你需要帮助，你需要给我更多关于你做了什么的信息。

Unity encapsulates audio, replaces AudioClip in the game with unit encapsulated audio, replaces TXT configuration file, and plays normally in AssetStudio GUI, indicating that the replacement is successful, but the game will exit.
Can you also add the pathid search function, the go to asset menu?

**Comment by Make1860** [comment]
Unit 2020.2, 2020.3.9 all failed. The game uses 2020.3.9

**Comment by Make1860** [comment]
There is no response frequently. You can't replace too much at a time. In addition, the packaging time is very long

**Comment by Make1860** [comment]
This is how I replaced the audio in assetbundleextractor, but now the game unity has been upgraded to 2020.3.9, assetbundleextractor can no longer be used

**Comment by Make1860** [comment]
Only your uabea can be used above 2019 version. Can you fix the above problem? Please.

**Comment by nesrak1** [comment]
You have a lot of different problems in one github issue but I'll try to respond to each one anyway

> Unity encapsulates audio, replaces AudioClip in the game with unit encapsulated audio, replaces TXT configuration file, and plays normally in AssetStudio GUI, indicating that the replacement is successful, but the game will exit.

I don't understand what you mean. Again, if you mean you built a unity project, exported from it, and imported raw/dump into another game, you still need to copy the data from resS yourself or it's not going to work. I'm also not sure what txt configuration file you mean (export/import dump txt?).

> Can you also add the pathid search function, the go to asset menu?

Sure

> There is no response frequently. You can't replace too much at a time. In addition, the packaging time is very long

You mean it freezes for a long time when compressing? This is an issue with the c# lzma library. This is a bit hard of an issue to fix since it's AssetsTools that does this, not UABEA.

**Comment by Make1860** [comment]
Yes, export / import dump TXT, which is what you understand. I have copied data from ress and encapsulated the audio in the resource file. In the 2019 version, I used uabe to replace the game BGM, pointing the BGM in the game to my encapsulated resource file
But now 2020.3.9, uabea can be replaced, but it will flash back in the game





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nesrak1/UABEA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nesrak1/UABEA] audio bug (#75)





 
You have a lot of different problems in one github issue but I'll try to respond to each one anyway
  
Unity encapsulates audio, replaces AudioClip in the game with unit encapsulated audio, replaces TXT configuration file, and plays normally in AssetStudio GUI, indicating that the replacement is successful, but the game will exit.
  
I don't understand what you mean. Again, if you mean you built a unity project, exported from it, and imported raw/dump into another game, you still need to copy the data from resS yourself or it's not going to work. I'm also not sure what txt configuration file you mean (export/import dump txt?).
  
Can you also add the pathid search function, the go to asset menu?
  
Sure
  
There is no response frequently. You can't replace too much at a time. In addition, the packaging time is very long
  
You mean it freezes for a long time when compressing? This is an issue with the c# lzma library. This is a bit hard of an issue to fix since it's AssetsTools that does this, not UABEA.

**Comment by Make1860** [comment]
Yes, export / import dump TXT, which is what you understand. I have copied data from ress and encapsulated the audio in the resource file. In the 2019 version, I used uabe to replace the game BGM, pointing the BGM in the game to my encapsulated resource file
But now 2020.3.9, uabea can be replaced, but it will flash back in the game

**Comment by Make1860** [comment]
The method is normal, at least the BGM can be successfully replaced when using uabe
UABEA can also, at least export / import dump TXT is normal, AssetStudio GUI can also correctly identify and play the replaced bgm, bu it will crash in the game
Can you see where this error is? The original game’s BGM is too bad





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nesrak1/UABEA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nesrak1/UABEA] audio bug (#75)





 
You have a lot of different problems in one github issue but I'll try to respond to each one anyway
  
Unity encapsulates audio, replaces AudioClip in the game with unit encapsulated audio, replaces TXT configuration file, and plays normally in AssetStudio GUI, indicating that the replacement is successful, but the game will exit.
  
I don't understand what you mean. Again, if you mean you built a unity project, exported from it, and imported raw/dump into another game, you still need to copy the data from resS yourself or it's not going to work. I'm also not sure what txt configuration file you mean (export/import dump txt?).
  
Can you also add the pathid search function, the go to asset menu?
  
Sure
  
There is no response frequently. You can't replace too much at a time. In addition, the packaging time is very long
  
You mean it freezes for a long time when compressing? This is an issue with the c# lzma library. This is a bit hard of an issue to fix since it's AssetsTools that does this, not UABEA.

**Comment by nesrak1** [comment]
Seems to be working fine for me on a unity 2020.3 game.

Here's what I did:

1. Created unity project in 2020.3
2. Dragged in audio file and added to scene
3. Built project
4. Rename sharedassets0.resource file to sharedassets0.resource.custom
5. Open sharedassets0.assets and export dump the audio asset to txt file
6. Edit dump and change sharedassets0.resource to sharedassets0.resource.custom
7. Copy sharedassets0.resource.custom to game I want to mod
8. Open sharedassets0.assets and import dump the txt file
9. Save and open game

This worked for me and I was able to change the audio without crash. I can't really tell what your issue is because I don't have enough information to help.

> AssetStudio GUI can also correctly identify and play the replaced bgm, bu it will crash in the game

I don't know then. You may try to verify you're exporting audio from editor version 2020.3 like the game is, but otherwise I don't know what the issue could be. In any case, I don't think this is an issue with UABEA (especially if AssetStudio can open it) but rather a version issue with your imported audio.

**Comment by Make1860** [comment]
The method I use is the same as yours. The game version is 2020.3.9, and the unity I use is also 2020.3.9. Audio can only be exported to wav format through AssetStudio, and what I encapsulate through untiy is also wav format. I can’t figure out the reason why Causes a crash, if there is a log, it will be fine

**Comment by Make1860** [comment]
The problem has been solved, but pathid search cannot be used. Can you add this function?

**Comment by nesrak1** [comment]
Added go to asset dialog
